In [28]:
my_list=[1,2,3,4,5]
c=[x*2 for x in my_list] 
print(c)
d=my_list*2
print(d)

[2, 4, 6, 8, 10]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [29]:
import numpy as np
arr = np.array([5, 10, 15])
x=arr>7
print(arr[x])
print(arr[(arr > 7) & (arr < 14)])

[10 15]
[10]


In [22]:
import numpy as np
arr=np.array([60,70,80,90])
x=np.array([65, 75, 85, 95])
print("the added sum is:",arr+x)
print("the difference id:",x-arr)
print("the increased percentage of term 1 :",arr*1.05)
print("the increased percentage of term 2:", x*1.05)

the added sum is: [125 145 165 185]
the difference id: [5 5 5 5]
the increased percentage of term 1 : [63.  73.5 84.  94.5]
the increased percentage of term 2: [68.25 78.75 89.25 99.75]


In [30]:
import numpy as np
total_marks=(arr+x)
print("the total marks is:",total_marks)
print("the marks greater than 150 is:",total_marks>150)
#the marks between 140 and 170 is:
print((total_marks>140)&(total_marks>170))
result=total_marks.sum()
print("the sum is:",result)
result=total_marks.mean()
print("the mean is:",result)
result=total_marks.max()
print("the max mark is:",result)
result=total_marks.min()
print("the min mark is:",result)
result=total_marks.std()
print("the standard deviation is:",result)

the total marks is: [ 5 11 16]
the marks greater than 150 is: [False False False]
[False False False]
the sum is: 32
the mean is: 10.666666666666666
the max mark is: 16
the min mark is: 5
the standard deviation is: 4.4969125210773475


In [31]:
import numpy as np
arr=np.array([[70, 80, 90],
[60, 75, 85]])
print(arr.sum(axis=0))
print(arr.sum(axis=1))


[130 155 175]
[240 220]


In [32]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
x = arr.reshape((2, 3))
print(x)
y = arr.ravel()
print(y)

(6,)
1
6
int64
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
