In [12]:
import numpy as  np
s=np.array([101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120])
print(s)
print(s.size)
print(s.dtype)
print(s.shape)
import numpy as np
e = np.ones((5, 5))
print("the attendence table of students:",e)
print("1 = Present")
print("0 = Absent")
print(e.ndim)
arr=np.zeros((4,3))
print("the initial score of 4 students :",arr)
#to include 6 evenly spaced points from 0 to 100
s=np.linspace(0,100,6)
print("the equal line spaced elements is:",s)
c=np.eye(5)
print("the identity matrix is:",c)
g=np.diag([2,4,6,8,10])
print("the diagonal matrix is:",g)


[101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118
 119 120]
20
int64
(20,)
the attendence table of students: [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 = Present
0 = Absent
2
the initial score of 4 students : [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
the equal line spaced elements is: [  0.  20.  40.  60.  80. 100.]
the identity matrix is: [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
the diagonal matrix is: [[ 2  0  0  0  0]
 [ 0  4  0  0  0]
 [ 0  0  6  0  0]
 [ 0  0  0  8  0]
 [ 0  0  0  0 10]]
