In [22]:
import numpy as np
print(np.random.rand(5))
print(np.random.randn(5))
x=np.random.randint(35,100,(3,4))
print("the random numbers are:",x)
students=[101,102,103,104,105]
#the choosen elements are:
print(np.random.choice(students,size=2))
np.random.seed(10)#the elements are fixed for the same desired output
print(np.random.rand(3))
arr=[10,20,30,40,50,60]
print(arr[3])#prints the third element 
print(arr[1:5])#prints elements from first index to fourth index
print(arr[-1])#prints the last element 
print(arr[::2])#prints every second element
print(arr[::-1])#the reversing of an array


[0.74880388 0.49850701 0.22479665 0.19806286 0.76053071]
[ 0.26551159  0.10854853  0.00429143 -0.17460021  0.43302619]
the random numbers are: [[84 86 89 48]
 [60 48 65 65]
 [47 66 92 71]]
[104 103]
[0.77132064 0.02075195 0.63364823]
40
[20, 30, 40, 50]
60
[10, 30, 50]
[60, 50, 40, 30, 20, 10]
