In [6]:
import numpy as np
sales=np.array([250.75, 300.40, 275.60, 400.90, 150.30, 500.50, 350.80])
print("the total sales is :")
print(np.sum(sales))
print("the mean of the sales is :")
print(np.mean(sales))
print("the median of the sales is:")
print(np.median(sales))
print("the standard deviation is :")
print(np.std(sales))
print("the minimum value of sales:")
print(np.min(sales))
print("the maximum no of sales:")
print(np.max(sales))
print("the floor to sales is:")
print(np.floor(sales))
print("the ceil to sales is:")
print(np.ceil(sales))
print("the round to sales is:")
print(np.round(sales))
print("the exponential growth of sales is:")
print(np.exp(sales))
print("the cumulative sum of sales is:")
print(np.cumsum(sales))
a=np.array( [[2, 1],
[3, 4]])
b =np.array( [[1, 2],
[5, 6]])
print("the matrix multiplication is :")
print(a@b)
print(np.dot(a,b))
print("the determinant of a is :")
print(np.linalg.det(a))
print("the inverse of a:")
inv_a = np.linalg.inv(a)
print(inv_a)
values,vectors=np.linalg.eig(a)
print("the eigen values:",values)
print("the eigen vectors:",vectors)
a=np.array([[2,1],[3,4]])
b=np.array([[5,11]])
x=np.linalg.solve(a,b)
print("the linear equation solved:",x)


the total sales is :
2229.25
the mean of the sales is :
318.4642857142857
the median of the sales is:
300.4
the standard deviation is :
104.2019766548385
the minimum value of sales:
150.3
the maximum no of sales:
500.5
the floor to sales is:
[250. 300. 275. 400. 150. 500. 350.]
the ceil to sales is:
[251. 301. 276. 401. 151. 501. 351.]
the round to sales is:
[251. 300. 276. 401. 150. 500. 351.]
the exponential growth of sales is:
[7.93124448e+108 2.89775967e+130 4.91540393e+119 1.28427431e+174
 1.88131115e+065 2.31413234e+217 2.24132199e+152]
the cumulative sum of sales is:
[ 250.75  551.15  826.75 1227.65 1377.95 1878.45 2229.25]
the matrix multiplication is :
[[ 7 10]
 [23 30]]
[[ 7 10]
 [23 30]]
the determinant of a is :
5.000000000000001
the inverse of a:
[[ 0.8 -0.2]
 [-0.6  0.4]]
the eigen values: [1. 5.]
the eigen vectors: [[-0.70710678 -0.31622777]
 [ 0.70710678 -0.9486833 ]]


ValueError: solve: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (m,m),(m,n)->(m,n) (size 1 is different from 2)