In [38]:
import numpy as np
marks = np.array([60,70,80,90,100])
x = np.array([[30, 50,70], [30, 40,80]])
y = np.array([[[10, 30, 40], [40, 50, 46]], [[47,48,49], [10, 50, 52]]])
arr=np.zeros((3,4))
s=np.ones((2,3))
exe=np.full((3,3),5)
b=np.arange(10,50,10)
c=np.linspace(0,100,5)
f=np.eye(4)
g=np.diag([10,20,30,40])
print(marks)
print(x)
print(y)
print(x.shape)
print(x.ndim)
print(x.dtype)
print(x.size)
print(arr)
print(s)
print(exe)
print(b)
print(c)
print(f)
print(g)





[ 60  70  80  90 100]
[[30 50 70]
 [30 40 80]]
[[[10 30 40]
  [40 50 46]]

 [[47 48 49]
  [10 50 52]]]
(2, 3)
2
int64
6
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5 5]
 [5 5 5]
 [5 5 5]]
[10 20 30 40]
[  0.  25.  50.  75. 100.]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]
