In [28]:
import numpy as np
print(np.random.rand(10))
attendance = np.array([0.2, 0.8, 0.6, 0.4, 0.9, 0.5, 0.7])
present = attendance[attendance > 0.5]
absent=attendance[attendance<0.5]
print("Present values:",present)
print("absent values:",absent)
x=np.random.randint(0,100,(15))
print("the random integers are:",x)
scores =x[x>60]
print("the score is higher:",scores)
y=x[x%5==0]
print("the score is divisible by 5:",y)
arr=np.array([100,200,300,400,500,600])
elements=[1,3,5]
print(arr[elements])
import numpy as np
matrix = np.random.randint(1, 51, (4, 4))
print("Matrix:",matrix)
print("2nd Row:")
print(matrix[1])
print("3rd Column:")
print(matrix[:, 2])
import numpy as np
uniform_values = np.random.uniform(0, 1, 5)
normal_values = np.random.normal(0, 1, 5)
print("Uniform Distribution Values:")
print(uniform_values)
print("Normal Distribution Values:")
print(normal_values)

[0.39262391 0.19039464 0.26502776 0.10199798 0.69421267 0.69525886
 0.75194091 0.44361552 0.23385737 0.71619641]
Present values: [0.8 0.6 0.9 0.7]
absent values: [0.2 0.4]
the random integers are: [93 29 29 51 28 58 62 53 82 72 36 87 58 77  8]
the score is higher: [93 62 82 72 87 77]
the score is divisible by 5: []
[200 400 600]
Matrix: [[24  4 50 37]
 [15 34 28 45]
 [47 41 41 49]
 [41  6 36 34]]
2nd Row:
[15 34 28 45]
3rd Column:
[50 28 41 36]
